### ISSUE TITLE
subnet_association and route_table_association as output variables

### ISSUE THREAD

**Issue by Kumar9676** [claranet/terraform-azurerm-subnet#5]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add subnet_association and route_table_association resource id's as output variables

### New or Affected Resource(s)/Data Source(s)

azurem_rm > 3.X.X

**Comment by Shr3ps** [comment]
Thanks for this issue,

can you open a PullRequest to add this?

**Comment by rossifumax** [comment]
Hello @Kumar9676 ,

Merged and tagged in [v6.3.0](https://github.com/claranet/terraform-azurerm-subnet/releases/tag/v6.3.0) !

Thanks for your contribution.
